"""add deleted_at to organizations

Revision ID: 59572441d9f4
Revises: 0001_create_organizations
Create Date: 2026-08-17 18:40:37.333854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59572441d9f4'
down_revision: Union[str, Sequence[str], None] = '0001_create_organizations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'deleted_at')
    # ### end Alembic commands ###
