"""make active user emails unique

Revision ID: c050d40e077b
Revises: 4bc99bd8a4b1
Create Date: 2026-08-22 14:47:58.188522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c050d40e077b'
down_revision: Union[str, Sequence[str], None] = '4bc99bd8a4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('ix_users_email_unique_active', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email_unique_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
